config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  # this gives all the routes we want for articles, we can take the only's off if we want to use all of the routes
  resources :articles, only: [:show, :index, :new, :create, :edit, :update,:destroy]
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/Article.rb
class Article < ApplicationRecord
   # this is a many to one which is the articles belonging to a user
  belongs_to :user
  #has many article categories
  has_many :article_categories
  #has many categories through the article categories database.
  #from this i can do @article.categories to display the categories
  # i can add categories to articles by using the shovel method <<. e.g "@article.categories << @category"
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum:100 }
  validates :description, presence: true, length: { minimum:10, maximum:300 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   #here i have used refactoring through these and added set:article for all the methods listed below
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def show
    
  end
 #i declare the pagination and give it rules so that it doesnt exceed 5 per page
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
    
    
  end
 #this instance variable is made to make a new article each time 
  def new
    @article = Article.new
  end

  def edit
    

  end
 #this create function is for the buttons which have been submitted
  #it makes an instance variable and the article params makes it a specific user_id
  def create
    @article = Article.new(article_params)
     #this allows the current user logged in to have this article in their name
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created succesfully."
      redirect_to article_path(@article)
    else 
      render 'new'
    

    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to article_path(@article)
    else
      render 'edit'

    end
  end

  def destroy   
    @article.destroy
    redirect_to articles_path
  end

  private
   #these are my refactored bits of code
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title,:description, category_ids: [])

  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "you can edit or delete your own articles only"
      redirect_to @article
    end
    
  end


end

app/views/articles/_article.html.erb
  <div class="container mb-5">
    <%# changed the articles to article instead of @article instance variable %>
    <% @articles.each do |article| %>
      <div class="row justify-content-md-center mt-10 pt-2 ">
      <div class="col-8">
        <div class="card text-center shadow  bg-white rounded mt-4 ">
          <div class="card-header font-italic ">
          <%# if its created by a user then it has the user who the article was made by via article.user.username %>
           <% if article.user %>
            By <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
            
            <% if article.categories.any? %>
           
            <div class = "mt-2">
              <%= render article.categories %>
            </div>


            <% end %>

            </div>
            <div class="card-body">
            <%# here it has the article title with a link and description with a length of 100 max to be shown %>
              <h5 class="card-title"><%= link_to article.title, article_path(article),class:"text-success" %></h5>
              <p class="card-text"><%= truncate(article.description,length:100) %></p>
              <%= link_to 'show', article_path(article),class: "btn btn-outline-info mt-2" %> </td>
              <%# here i made an if statement so that if the user is logged in and the user who the article
              was made is = to the current user logged in, they will be able to edit or delete the article %>
              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to 'edit', edit_article_path(article),class: "btn btn-success mt-2" %> </h2>
                <%= link_to 'Delete', article_path(article), class:"btn btn-danger mt-2", method: :delete, data:{confirm:"are you sure?" } %> </h2>
              <% end %>      
            </div>
            <div class="card-footer text-muted">
            <%# created time ago in words make it more neat and article.created at gives the time it was created %>
            <small> Created <%= time_ago_in_words(article.created_at) %> ago,
            Edited <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>           
          </div>
        </div>
      </div>     
    <% end %>
  </div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%# the object is the class youre working with within this html page %>
      <%= render 'shared/errors', obj: @article %>
      <%# the model is the instance variable or class which in this case is article %>
      <%= form_with(model: @article, class:"shadow p-3 mb-3 bg-info rounded",local: true)  do |f| %>
        <div class="form-group row">
          <%# f.label is short for article label which is the title  %>
          <%= f.label :title ,class:"col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class:"form-control shadow rounded",placeholder:"Title of article" %>
          </div> 
        </div>

      <div class="form-group row">
      <%# f.label is short for article label which is the description in this instance  %>
        <%= f.label :description,class:"col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_area :description, rows:5, class:"form-control shadow rounded",placeholder:"Description of article" %>
        </div>
      </div>  

      <div class="form-group row">
      <%# f.label is short for article label which is the description in this instance  %>
        <%= f.label :category,class:"col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.collection_select(:category_ids,Category.all, :id, :name,
          {prompt: "make your selection from the list below (can be empty)"},
          {multiple: true , size: 3 , class: "custom-select shadow rounded" } ) %>
        </div>
      </div>  

      <div class="form-group row justify-content-center">
      <%# here we have the submit button which works according to the controller  %>
        <%= f.submit class:"btn btn-outline-light btn-lg" %>
      </div>
      <% end %>
    </div>
    <div class="mb-3">
    <%# i have put a link here for the user to have the option to go back to the articles listing page  %>
    <%= link_to '[ Return to articles listing page ]', articles_path, class:"text-info" %>
    </div>
  </div>
  </div>

app/views/articles/edit.html.erb
<h1 class = "text-center mt-4"> Create New Article </h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class = "text-center mt-4"> Listing Articles </h1>
  <%# pagination is for when the user or page has a lot of articles. it will allow us to
  go to different pages and not have all the articles in only one page. %>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

  <%= render 'article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class = "text-center mt-4"> Create A New Article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class = "text-center mt-4"> <%= @article.title %> </h2>
  <div class="container">
    <%# instance variable here is @article  %>
      <div class="row justify-content-md-center mt-10 pt-2">
      <div class="col-8">
        <div class="card text-center shadow  bg-white rounded mt-4">
          <div class="card-header font-italic">
          <%# here we are saying who the article is created by via the username if there is a user  %>
            By <%= @article.user.username if @article.user %>
            <%#this is the image, which is found via the specific user @article.user, if it is clicked
            it will take the person to the users profile  %>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            <% if @article.categories.any? %>
           
            <div class = "mt-2">
              <%= render @article.categories %>
            </div>


            <% end %>
            </div>
            <div class="card-body">
              <%# here we have the full description shown in a simple format which displays from left to right  %>
              <div class="card-text text-left"><%= simple_format(@article.description) %></div>
              <%# if theres someone logged in and the @article.user which is the instance
              variable is = to the current user logged in only then will the user be able
              to edit or delete the article based on if it was created by them.  %>
              <% if logged_in? && (@article.user == current_user ||current_user.admin?) %>
                <%= link_to 'edit', edit_article_path(@article),class: "btn btn-success mt-2" %> </h2>
                <%= link_to 'Delete', article_path(@article), class:"btn btn-danger mt-2", method: :delete, data:{confirm:"are you sure?" } %> </h2>
              <% end %>
            </div>
            <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(@article.created_at) %> ago,
            Edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
            </div>           
          </div>
        </div>
      </div>  
      <div class="mb-3">   
      <%= link_to '[ Return to articles listing page ]', articles_path, class:"text-info row justify-content-md-center mt-4" %>
    </div>
   
  </div>