config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  # this gives all the routes we want for articles, we can take the only's off if we want to use all of the routes
  resources :articles, only: [:show, :index, :new, :create, :edit, :update,:destroy]
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/views/pages/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50 fixed-bottom">
      <div class="container text-center >
        <small id="copyright">Copyright &copy; <a class= "text-white", href="http://localhost:3000">link text</a></small>
      </div>
</footer>

app/views/pages/_jumbotron.html.erb
<div class="container" id="home-container">
    <%# this is what is put in the middle of the page if it is rendered,
    in this case i have put a signup link in this page and a photo in the background  %>
    <div class="jumbotron text-center">
      <h1 class="display-4"id="alpha-blog">Alpha Blog</h1>
      <p class="lead" id="the-lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p id="color4">It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>

app/views/pages/about.html.erb
<h1>about page</h1>

<%= link_to 'Articles listing page', articles_path %>
<%= link_to 'home', root_path %>

app/views/pages/home.html.erb
<div id="page-content">
</div>

<%= render 'pages/jumbotron' %>


<div class="fixed-bottom">
</div>