config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  # this gives all the routes we want for articles, we can take the only's off if we want to use all of the routes
  resources :articles, only: [:show, :index, :new, :create, :edit, :update,:destroy]
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/category.rb
class Category < ApplicationRecord
#rails generate migration create_categories, this will be the code i write to create a database for categories. same code will be written for users or articles etc.
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  #forming the associations for article categories and 
  #articles through the article categories
  has_many :article_categories
  #from this i can do @category.articles to display the articles
  has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id]) 
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
  <%= link_to category.name, category_path(category) ,class: "badge badge-info mr-1" %> 
  

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%# the object is the class youre working with within this html page %>
      <%= render 'shared/errors', obj: @category %>
      <%# the model is the instance variable or class which in this case is article %>
      <%= form_with(model: @category, class:"shadow p-3 mb-3 bg-info rounded",local: true)  do |f| %>
        <div class="form-group row">
          <%# f.label is short for article label which is the title  %>
          <%= f.label :name, "Category Name" ,class:"col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class:"form-control shadow rounded",placeholder:"enter a name" %>
          </div> 
        </div>

      
      <div class="form-group row justify-content-center">
      <%# here we have the submit button which works according to the controller  %>
        <%= f.submit class:"btn btn-outline-light btn-lg" %>
      </div>
      <% end %>
    </div>
    <div class="mb-3">
    <%# i have put a link here for the user to have the option to go back to the articles listing page  %>
    <%= link_to '[ Return to category page]' , category_path(@category), class:"text-info" %>
    </div>
  </div>
  </div>

app/views/categories/edit.html.erb
<h1 class = "text-center mt-4"> edit your Category </h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class = "text-center mt-4"> Create A Category </h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class = "text-center mt-4"> Category: <%= @category.name %> </h1>
<div class = "container">

<div class="text-center mt-4">
<%#  this is the code for when i want a specific user to only be able to do an action like edit or delete %>
 <% if logged_in? && current_user.admin?  %>
  <%= link_to "Edit Category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  <% end %>

</div>

<h3 class = "text-center mt-4"> Articles </h3>
<%#  pagination here refers to @articles instance variable because that is the list i am looking for %>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>  

<%= render 'articles/article' %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>  

</div>