config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  # this gives all the routes we want for articles, we can take the only's off if we want to use all of the routes
  resources :articles, only: [:show, :index, :new, :create, :edit, :update,:destroy]
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50 bottom" >
      <div class="container text-center" >
        <small> Copyright &copy; <%= link_to "articles_path", articles_path, class: "text-white" %> </small>
      </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        <%end%>
        
        <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        <%end%>

        
    </div>
  <% end %>
 </div> 

  

app/views/layouts/_navigation.html.erb
<div class="navbar-dark bg-dark">
  <nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <%#  this is just a normal link to the home page from ay page when alpha blog is clicked %>
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">         
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
          </a>
          <div class="dropdown-menu " aria-labelledby="navbarDropdown">              
            <% if logged_in? %>
             <%= link_to "Create new Article", new_article_path,class: "dropdown-item" %>
            <% end %>
            <%= link_to "View Articles", articles_path,class: "dropdown-item" %>
            
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu " aria-labelledby="navbarDropdown">              
            <% if logged_in? && current_user.admin? %>
            
             <%= link_to "Create new Category", new_category_path,class: "dropdown-item" %>
            <% end %>
            <%= link_to "View Categories", categories_path,class: "dropdown-item" %>
          </div>
        </li>

        <%# if theres a user logged in, the current_user.username will have the username of the user written
        down an the user_path will allow the user to be shown if the name is clicked on, 
        the link to logout allows the user to use the destroy function which allows them to
        log out of the session  %>
        <% if logged_in? %>
          
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "Admin" if current_user.admin? %> profile[<%=current_user.username%>]
          </a>

          <div class="dropdown-menu " aria-labelledby="navbarDropdown">              
            <%= link_to "view your profile", user_path(current_user),class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user),class: "dropdown-item" %>
            <%= link_to "Logout", logout_path, class: "dropdown-item", method: :delete %>
            <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "are you sure?"} %>
          </div>
        </li>
       <%#  here we have the else functio which will only work if there is nobody logged in,
       it will have a login with its path and a signup with its path %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "SignUp", signup_path, class: "nav-link" %>
          </li>

        <% end %>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<%# everything written here will be shown in the entire app  %>
  <body class="d-flex flex-column">
  <%= render 'layouts/navigation' %>
  <div id="page-content">
    <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
  </div>    
  </body>
</html>